=== servicetitan/request-middleware-templates/subaccount/response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "subaccount.response",
  "type": "object",
  "description": "Response for activating a customer's vendor account",
  "additionalProperties": false,
  "properties": {
    "errorCode": {
      "type": [
        "null",
        "string"
      ],
      "description": "Error code returned from the vendor's API, if any"
    },
    "callBackInfo": {
      "description": "Optional callback information to be used in the next request. Only present if a callback is needed",
      "oneOf": [
        {
          "type": "null"
        },
        {
          "$ref": "#/definitions/CallbackInfo"
        }
      ]
    },
    "success": {
      "type": "boolean"
    },
    "errorKind": {
      "type": [
        "null",
        "string"
      ]
    },
    "message": {
      "type": [
        "null",
        "string"
      ]
    },
    "errorMessage": {
      "type": [
        "null",
        "string"
      ]
    },
    "subAccounts": {
      "type": "array",
      "description": "Customer's vendor account's subaccounts information",
      "items": {
        "$ref": "#/definitions/VendorSubAccountDto"
      }
    },
    "$schema": {
      "type": "string",
      "default": "./subaccount.response.schema.json"
    }
  },
  "definitions": {
    "CallbackInfo": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "shouldCallback": {
          "type": "boolean",
          "description": "Controls whether another request should be made"
        },
        "values": {
          "type": [
            "null",
            "object"
          ],
          "description": "Generic object to be passed to the next request\nUsed for passing data between chained requests",
          "additionalProperties": {}
        },
        "maxCallbacksForRequest": {
          "type": [
            "integer",
            "null"
          ],
          "format": "int32"
        }
      }
    },
    "VendorSubAccountDto": {
      "type": "object",
      "description": "Model representing a customer's vendor subAccount associated with their vendor account",
      "additionalProperties": false,
      "properties": {
        "subAccountId": {
          "type": "string",
          "description": "Customer's vendor subAccount Id"
        },
        "name": {
          "type": "string",
          "description": "Name associated with the subAccount"
        },
        "postalCode": {
          "type": [
            "null",
            "string"
          ],
          "description": "Postal Code associated with the subAccount"
        },
        "customFields": {
          "type": "object",
          "description": "Any custom fields to display to user for this subAccount",
          "additionalProperties": {
            "type": "string"
          }
        },
        "vendorIdentifiers": {
          "type": [
            "null",
            "object"
          ],
          "description": "A map of identifiers specific to the Vendor, which will be passed back to the vendor on subsequent calls",
          "additionalProperties": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== servicetitan/request-middleware-templates/st-schemas/subaccount/response.sample.json
{
  "errorCode": "errorCode",
  "callBackInfo": null,
  "success": false,
  "errorKind": "errorKind",
  "message": "message",
  "errorMessage": "errorMessage",
  "subAccounts": [
    {
      "subAccountId": "subAccountId",
      "name": "name",
      "postalCode": "postalCode",
      "customFields": {}
    }
  ],
  "$schema": "./subaccount.response.schema.json"
}

=== servicetitan/request-middleware-templates/subaccount/response.sample.json
{
  "errorCode": "errorCode",
  "callBackInfo": null,
  "success": false,
  "errorKind": "errorKind",
  "message": "message",
  "errorMessage": "errorMessage",
  "subAccounts": [
    {
      "subAccountId": "subAccountId",
      "name": "name",
      "postalCode": "postalCode",
      "customFields": {},
      "vendorIdentifiers": {}
    }
  ],
  "$schema": "./subaccount.response.schema.json"
}
