=== servicetitan/request-middleware-templates/field-configuration-CallbackName/response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "field-configuration-{CallbackName}.response",
  "type": "object",
  "description": "Response for dynamic endpoint pattern: field-configuration-{CallbackName}\n\nResponse for retrieving a purchase order field dynamic configuration",
  "additionalProperties": false,
  "properties": {
    "errorCode": {
      "type": [
        "null",
        "string"
      ],
      "description": "Error code returned from the vendor's API, if any"
    },
    "callBackInfo": {
      "description": "Optional callback information to be used in the next request. Only present if a callback is needed",
      "oneOf": [
        {
          "type": "null"
        },
        {
          "$ref": "#/definitions/CallbackInfo"
        }
      ]
    },
    "success": {
      "type": "boolean"
    },
    "errorKind": {
      "type": [
        "null",
        "string"
      ]
    },
    "message": {
      "type": [
        "null",
        "string"
      ]
    },
    "errorMessage": {
      "type": [
        "null",
        "string"
      ]
    },
    "options": {
      "type": "array",
      "description": "Options to display for fields that are dropdowns or fixed option sets.",
      "items": {
        "$ref": "#/definitions/VendorPurchaseOrderDynamicOptionDto"
      }
    },
    "isVisible": {
      "type": [
        "boolean",
        "null"
      ],
      "description": "If true or unspecified, the field will be shown to the user. If false, the field is hidden.\nCan be used to hide fields based off of values of other fields"
    },
    "isRequired": {
      "type": [
        "boolean",
        "null"
      ],
      "description": "If true, the field will be required to send an electronic purchase order.\nIf false, the field is optional.\nIf unspecified, will revert to the default setting for the field in the vendor configuration."
    },
    "defaultValue": {
      "type": [
        "null",
        "string"
      ],
      "description": "The default value to pre-populate the field with, if any"
    },
    "$schema": {
      "type": "string",
      "default": "./field-configuration-CallbackName.response.schema.json"
    }
  },
  "definitions": {
    "CallbackInfo": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "shouldCallback": {
          "type": "boolean",
          "description": "Controls whether another request should be made"
        },
        "values": {
          "type": [
            "null",
            "object"
          ],
          "description": "Generic object to be passed to the next request\nUsed for passing data between chained requests",
          "additionalProperties": {}
        },
        "maxCallbacksForRequest": {
          "type": [
            "integer",
            "null"
          ],
          "format": "int32"
        }
      }
    },
    "VendorPurchaseOrderDynamicOptionDto": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "description": "The identifier/value to send back on pricing or purchase order calls when this option is selected"
        },
        "name": {
          "type": "string",
          "description": "The option display name to display to the user"
        },
        "cost": {
          "type": [
            "null",
            "number"
          ],
          "description": "For line-item fields, selecting this option will change the price of the item to the value specified",
          "format": "decimal"
        }
      }
    }
  },
  "x-endpoint-pattern": "field-configuration-{CallbackName}",
  "x-is-wildcard": true
}

=== servicetitan/request-middleware-templates/field-configuration-CallbackName/response.sample.json
{
  "errorCode": "errorCode",
  "callBackInfo": null,
  "success": false,
  "errorKind": "errorKind",
  "message": "message",
  "errorMessage": "errorMessage",
  "options": [
    {
      "id": "id",
      "name": "name",
      "cost": 0.0
    }
  ],
  "isVisible": false,
  "isRequired": false,
  "defaultValue": "defaultValue",
  "$schema": "./field-configuration-CallbackName.response.schema.json"
}
