=== servicetitan/request-middleware-templates/branches/response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "branches.response",
  "type": "object",
  "description": "Response for retrieving vendor branches",
  "additionalProperties": false,
  "properties": {
    "errorCode": {
      "type": [
        "null",
        "string"
      ],
      "description": "Error code returned from the vendor's API, if any"
    },
    "callBackInfo": {
      "description": "Optional callback information to be used in the next request. Only present if a callback is needed",
      "oneOf": [
        {
          "type": "null"
        },
        {
          "$ref": "#/definitions/CallbackInfo"
        }
      ]
    },
    "success": {
      "type": "boolean"
    },
    "errorKind": {
      "type": [
        "null",
        "string"
      ]
    },
    "message": {
      "type": [
        "null",
        "string"
      ]
    },
    "errorMessage": {
      "type": [
        "null",
        "string"
      ]
    },
    "branches": {
      "type": "array",
      "description": "List of branch information",
      "items": {
        "$ref": "#/definitions/VendorBranchDto"
      }
    },
    "$schema": {
      "type": "string",
      "default": "./branches.response.schema.json"
    }
  },
  "definitions": {
    "CallbackInfo": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "shouldCallback": {
          "type": "boolean",
          "description": "Controls whether another request should be made"
        },
        "values": {
          "type": [
            "null",
            "object"
          ],
          "description": "Generic object to be passed to the next request\nUsed for passing data between chained requests",
          "additionalProperties": {}
        },
        "maxCallbacksForRequest": {
          "type": [
            "integer",
            "null"
          ],
          "format": "int32"
        }
      }
    },
    "VendorBranchDto": {
      "type": "object",
      "description": "Model representing a branch",
      "additionalProperties": false,
      "properties": {
        "branchId": {
          "type": "string",
          "description": "Vendor's identifier for the branch"
        },
        "branchName": {
          "type": "string",
          "description": "Name of the branch"
        },
        "pricingGroup": {
          "type": [
            "null",
            "string"
          ],
          "description": "Customer's pricing group e.g. MainStoreCode"
        },
        "phoneNumber": {
          "type": [
            "null",
            "string"
          ],
          "description": "Branch's phone number"
        },
        "contact": {
          "type": [
            "null",
            "string"
          ],
          "description": "Contact information for the branch"
        },
        "address": {
          "description": "Address information for the branch",
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/AddressDto"
            }
          ]
        },
        "vendorIdentifiers": {
          "type": [
            "null",
            "object"
          ],
          "description": "A map of identifiers specific to the Vendor, which will be passed back to the vendor on subsequent calls",
          "additionalProperties": {
            "type": "string"
          }
        },
        "latitude": {
          "type": [
            "null",
            "number"
          ],
          "description": "Latitude",
          "format": "double"
        },
        "longitude": {
          "type": [
            "null",
            "number"
          ],
          "description": "Longitude",
          "format": "double"
        }
      }
    },
    "AddressDto": {
      "type": "object",
      "description": "Object to represent an address",
      "additionalProperties": false,
      "properties": {
        "street": {
          "type": [
            "null",
            "string"
          ],
          "description": "Street"
        },
        "unit": {
          "type": [
            "null",
            "string"
          ],
          "description": "Unit"
        },
        "city": {
          "type": [
            "null",
            "string"
          ],
          "description": "City"
        },
        "state": {
          "type": [
            "null",
            "string"
          ],
          "description": "State"
        },
        "postalCode": {
          "type": [
            "null",
            "string"
          ],
          "description": "Postal code"
        },
        "country": {
          "type": [
            "null",
            "string"
          ],
          "description": "Country"
        },
        "isVendorAddress": {
          "type": "boolean",
          "description": "IsVendorAddress"
        },
        "addressId": {
          "type": [
            "null",
            "string"
          ],
          "description": "AddressId"
        }
      }
    }
  }
}

=== servicetitan/request-middleware-templates/st-schemas/branches/response.sample.json
{
  "errorCode": "errorCode",
  "callBackInfo": null,
  "success": false,
  "errorKind": "errorKind",
  "message": "message",
  "errorMessage": "errorMessage",
  "branches": [
    {
      "branchId": "branchId",
      "branchName": "branchName",
      "pricingGroup": "pricingGroup",
      "phoneNumber": "phoneNumber",
      "contact": "contact",
      "address": null,
      "vendorIdentifiers": {},
      "latitude": 0.0,
      "longitude": 0.0
    }
  ],
  "$schema": "./branches.response.schema.json"
}
