=== servicetitan/request-middleware-templates/st-schemas/field-configuration-callbackname/request.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "field-configuration-callbackname.request",
  "type": "object",
  "description": "Request for retrieving vendor purchase order dynamic options to be used in a dropdown field on the purchase order",
  "additionalProperties": false,
  "properties": {
    "accountId": {
      "type": "string",
      "description": "The main account identifier for the supplier"
    },
    "customIdentifierFields": {
      "type": [
        "null",
        "object"
      ],
      "description": "A collection of identifiers specific to the Vendor.\nThese were either previously returned by the vendor, or configured by the user based on vendor-specific inputs",
      "additionalProperties": {
        "type": "string"
      }
    },
    "vendorId": {
      "type": "string"
    },
    "callbackData": {
      "type": [
        "null",
        "object"
      ],
      "description": "Generic data that is specified by the previous request's CallbackInfo",
      "additionalProperties": {}
    },
    "callbackName": {
      "type": "string",
      "description": "The identifier for the dynamically configured field. This will be used to determine which field's options are being requested"
    },
    "purchaseOrder": {
      "description": "Current data for the purchase order at the time of the request. Entered by the user",
      "oneOf": [
        {
          "$ref": "#/definitions/PurchaseOrder"
        }
      ]
    }
  },
  "definitions": {
    "PurchaseOrder": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "supplierBranchId": {
          "type": [
            "null",
            "string"
          ]
        },
        "dateRequired": {
          "type": "string",
          "format": "date-time"
        },
        "amount": {
          "type": "number",
          "format": "decimal"
        },
        "shipTo": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/InventoryAddressModel"
            }
          ]
        },
        "isVendorCounterPickup": {
          "type": "boolean"
        },
        "lineItems": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/PurchaseOrderLineItemModel"
          }
        },
        "dynamicHeaderFields": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/DynamicFieldModel"
          }
        }
      }
    },
    "InventoryAddressModel": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": [
            "null",
            "string"
          ]
        },
        "fullAddress": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/AddressModel"
            }
          ]
        }
      }
    },
    "AddressModel": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "street": {
          "type": [
            "null",
            "string"
          ]
        },
        "unit": {
          "type": [
            "null",
            "string"
          ]
        },
        "city": {
          "type": [
            "null",
            "string"
          ]
        },
        "state": {
          "type": [
            "null",
            "string"
          ]
        },
        "zip": {
          "type": [
            "null",
            "string"
          ]
        },
        "country": {
          "type": [
            "null",
            "string"
          ]
        },
        "latitude": {
          "type": [
            "null",
            "number"
          ],
          "format": "double"
        },
        "longitude": {
          "type": [
            "null",
            "number"
          ],
          "format": "double"
        }
      }
    },
    "PurchaseOrderLineItemModel": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": [
            "null",
            "string"
          ]
        },
        "quantity": {
          "type": "number",
          "format": "decimal"
        },
        "cost": {
          "type": "number",
          "format": "decimal"
        },
        "vendorPartNumber": {
          "type": [
            "null",
            "string"
          ]
        },
        "externalId": {
          "type": [
            "null",
            "string"
          ]
        },
        "skuCatalogId": {
          "type": [
            "null",
            "string"
          ]
        },
        "chargeable": {
          "type": "boolean"
        },
        "inventoryLocation": {
          "type": [
            "null",
            "string"
          ]
        },
        "dynamicLineItemFields": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/DynamicFieldModel"
          }
        }
      }
    },
    "DynamicFieldModel": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "internalName": {
          "type": [
            "null",
            "string"
          ]
        },
        "isRequired": {
          "type": "boolean"
        },
        "value": {
          "type": [
            "null",
            "string"
          ]
        },
        "type": {
          "type": [
            "null",
            "string"
          ]
        }
      }
    }
  }
}

=== servicetitan/request-middleware-templates/st-schemas/field-configuration-callbackname/request.sample.json
{
  "accountId": "accountId",
  "customIdentifierFields": {},
  "vendorId": "vendorId",
  "callbackData": {},
  "callbackName": "callbackName",
  "purchaseOrder": {
    "supplierBranchId": "supplierBranchId",
    "dateRequired": "2025-10-03T20:29:51.9297927+00:00",
    "amount": 0.0,
    "shipTo": null,
    "isVendorCounterPickup": false,
    "lineItems": [
      {
        "name": "name",
        "quantity": 0.0,
        "cost": 0.0,
        "vendorPartNumber": "vendorPartNumber",
        "externalId": "externalId",
        "skuCatalogId": "skuCatalogId",
        "chargeable": false,
        "inventoryLocation": "inventoryLocation",
        "dynamicLineItemFields": [
          {
            "id": 0,
            "internalName": "internalName",
            "isRequired": false,
            "value": "value",
            "type": "type"
          }
        ]
      }
    ],
    "dynamicHeaderFields": [
      {
        "id": 0,
        "internalName": "internalName",
        "isRequired": false,
        "value": "value",
        "type": "type"
      }
    ]
  }
}
